# PyTorch Tensor Exercises
This notebook demonstrates basic tensor operations as described in the handout.

In [12]:
import torch

## Create a tensor from a nested list

In [13]:
data = [[5, 3], [0, 9]]
x_data = torch.tensor(data)
x_data

tensor([[5, 3],
        [0, 9]])

## Create a tensor of shape (5, 4) with random numbers from [0, 1)

In [14]:
t = torch.rand((5,4))
t

# 5 rows, 4 columns # rxc

tensor([[0.3937, 0.3966, 0.4791, 0.7288],
        [0.9962, 0.7743, 0.0061, 0.1569],
        [0.2128, 0.8642, 0.5378, 0.5037],
        [0.1909, 0.3153, 0.3075, 0.5933],
        [0.9307, 0.5804, 0.6595, 0.2107]])

## Find out which device the tensor 't' is on and its datatype

In [15]:
print(t.device)  # cpu
print(t.dtype)   # float32

cpu
torch.float32


## Create two random tensors u and v of shape (4, 4) and join them to make a tensor of shape (8, 4)

In [16]:
u = torch.randn((4,4))
v = torch.randn((4,4))
print(torch.concat((u,v), dim=0).shape)  # torch.Size([8, 4])

torch.Size([8, 4])


### Why use dim=0 in torch.concat?
- `dim=0` concatenates along the first dimension (rows), stacking u and v vertically to get shape (8, 4).
- If you use `dim=1`, tensors are concatenated along columns, resulting in shape (4, 8) (if shapes are compatible).
- For 2D tensors, `dim=0` is rows, `dim=1` is columns.
- `dim=2` would only be valid for 3D tensors, concatenating along the third dimension.

**Summary:**
- `dim=0`: vertical stack (row-wise)
- `dim=1`: horizontal stack (column-wise)
- `dim=2`: depth stack (for 3D tensors)

## Join u and v to create a tensor of shape (2, 4, 4)

In [17]:
print(torch.stack((u,v), dim=0).shape)  # torch.Size([2, 4, 4])

torch.Size([2, 4, 4])


### What does torch.stack do?
- `torch.stack` joins a sequence of tensors along a new dimension.
- Unlike `torch.concat`, which merges along an existing axis, `torch.stack` creates a new axis.
- Example: stacking two (4, 4) tensors with `dim=0` gives shape (2, 4, 4).
- Each original tensor becomes a slice along the new dimension.
- Useful for batching or grouping tensors together.

## Join u and v to make a tensor w of shape (4, 4, 2)

In [18]:
w = torch.stack((u,v), dim=2)
print(w.shape)  # torch.Size([4, 4, 2])

torch.Size([4, 4, 2])


### Difference between torch.stack with dim=0 and dim=2
- `torch.stack((u, v), dim=0)` creates a new first dimension, resulting in shape (2, 4, 4). Each tensor becomes a slice along the new axis (like stacking into a batch).
- `torch.stack((u, v), dim=2)` creates a new third dimension, resulting in shape (4, 4, 2). Here, each original tensor is stacked along the last axis, so each (i, j) position contains a 2-element vector from u and v.
- Use `dim=0` for batching/grouping tensors; use `dim=2` for combining tensors along the innermost axis.

## Index w at 3, 3, 0. Call that element 'e'

In [19]:
e = w[3,3,0]
e

tensor(0.5720)

## Which of u or v would you find w in? Verify.

In [20]:
w[3,3,0] == u[3,3]  # True

tensor(True)

## Tensor of ones and elementwise multiplication

In [21]:
a = torch.ones((4,3))
a * a  # Elementwise multiplication

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
a * a  # tensor([[1., 1., 1.],[1., 1., 1.],[1., 1., 1.],[1., 1., 1.]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Example: a = [1, 2, 3] — Compare a * a and a @ a

In [ ]:
a = torch.tensor([1, 2, 3])
print('a * a:', a * a)  # Elementwise: [1, 4, 9]
print('a @ a:', a @ a)  # Dot product: 1*1 + 2*2 + 3*3 = 14

### What happens if you do a * a.T?

In [ ]:
try:
    result = a * a.T
except Exception as e:
    print('Error:', e)  # This will print an error because shapes do not match for elementwise multiplication

### Difference between a * a and a @ a
- `a * a` performs elementwise multiplication. Each element is multiplied with its corresponding element.
- `a @ a` performs matrix multiplication (dot product). It multiplies rows of `a` with columns of `a` and sums the products.
- Elementwise: shape stays the same. Matrix multiplication: shape changes according to matrix rules.

## Add an extra dimension to 'a'

In [23]:
print(torch.unsqueeze(a, 0).shape)  # torch.Size([1, 4, 3])

torch.Size([1, 4, 3])


## Matrix multiplication of a with its transpose

In [24]:
a @ a.T  # tensor([[3., 3., 3., 3.],[3., 3., 3., 3.],[3., 3., 3., 3.],[3., 3., 3., 3.]])

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

## What would a.mul(a) result in?
Elementwise multiplication, same as a * a.

In [ ]:
a.mul(a)  # Elementwise multiplication, same as a * a


# a * a is elementwise multiplication (each element with itself).
# a @ a is matrix multiplication (dot product, row with column).

# a=[1,2,3] a*a=[1,4,9]
# a@a=1+4=9=14

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## What would a.matmul(a.T) result in?
Matrix multiplication (dot product), same as a @ a.T.

In [26]:
a.matmul(a.T)  # Matrix multiplication, same as a @ a.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

## What would a.mul(a.T) result in?
An error; the sizes won’t match for elementwise multiplication.

In [27]:
# Uncomment to see the error
# a.mul(a.T)

## Guess what the following will print. Verify

In [28]:
t = torch.ones(5)
n = t.numpy()
n[0] = 2
print(t)  # tensor([2., 1., 1., 1., 1.]) Changes in the NumPy array reflect in the tensor.

tensor([2., 1., 1., 1., 1.])


## What will the following print?

In [30]:
t = torch.tensor([2., 1., 1., 1., 1.])
t.add(2)
print(t.numpy()) 
t.add_(1)
print(t.numpy())  # [3. 2. 2. 2. 2.]

[2. 1. 1. 1. 1.]
[3. 2. 2. 2. 2.]


### Difference between t.add(2) and t.add_(1)
- `t.add(2)` returns a new tensor with 2 added to each element, but does not modify `t`.
- `t.add_(1)` adds 1 to each element of `t` in-place, modifying the original tensor.
- The underscore (`_`) in `add_` means the operation is in-place.